name: Deploy Angular app to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Chọn version Node.js phù hợp với Angular

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build Angular app
      - name: Build Angular app
        run: npm run build --prod
        # Mặc định Angular build ra dist/<project-name>
        # Nếu bạn dùng Angular 15+, lệnh vẫn tương tự

      # Setup GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Upload artifact (chỉ upload thư mục dist/<project-name>)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist/ndmthuan97.github.io'

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
