name: Deploy Angular app to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js 24
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24'

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Install Angular CLI globally
      - name: Install Angular CLI
        run: npm install -g @angular/cli

      # Build Angular app
      - name: Build Angular app
        run: |
          PROJECT_NAME="CV" # Thay bằng tên project trong angular.json
          REPO_NAME=$(basename $GITHUB_REPOSITORY)
          echo "Building project $PROJECT_NAME for repo $REPO_NAME"

          # Build production với base-href đúng
          ng build --configuration production --base-href /$REPO_NAME/

          # Copy index.html → 404.html để SPA reload không bị 404
          cp dist/$PROJECT_NAME/index.html dist/$PROJECT_NAME/404.html

      # Setup GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Upload artifact (chỉ upload thư mục build)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/CV

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
